alg = input('DIGITE ALGO: ')
print('identifier - ',alg.isidentifier())
print('decimal - ',alg.isdecimal())
print('alnum - ',alg.isalnum())
print('alpha - ',alg.isalpha())
print('digit - ',alg.isdigit())
print('lower - ',alg.islower())
print('numeric - ',alg.isnumeric())
print('printable - ',alg.isprintable())
print('space - ',alg.isspace())
print('title - ',alg.istitle())
print('upper - ',alg.isupper())
